// Action Types

const actionTypes = {
    // Application level actions
    UPDATE_FIELD_VALUE: "UPDATE_FIELD_VALUE",
    // Service related actions
    SHOW_SERVICE_FORM: "SHOW_SERVICE_FORM",
    HIDE_SERVICE_FORM: "HIDE_SERVICE_FORM",
    SAVE_SERVICE_STARTED: "SAVE_SERVICE_STARTED",
    SAVE_SERVICE_SUCCESS: "SAVE_SERVICE_SUCCESS",
    SAVE_SERVICE_FAILURE: "SAVE_SERVICE_FAILURE",

    // Service list related actions
    FETCH_SERVICES_STARTED: "FETCH_SERVICES_STARTED",
    FETCH_SERVICES_SUCCESS: "FETCH_SERVICES_SUCCESS",
    FETCH_SERVICES_FAILURE: "FETCH_SERVICES_FAILURE",
    UPDATE_QUERY: "UPDATE_QUERY",
    SET_FILTERED_SERVICES: "SET_FILTERED_SERVICES",

}

export default actionTypes;
