// Action Types

const actionTypes = {
    SHOW_SERVICE_FORM: "SHOW_SERVICE_FORM",
    HIDE_SERVICE_FORM: "HIDE_SERVICE_FORM",
    FETCH_SERVICES_STARTED: "FETCH_SERVICES_STARTED",
    FETCH_SERVICES_SUCCESS: "FETCH_SERVICES_SUCCESS",
    FETCH_SERVICES_FAILURE: "FETCH_SERVICES_FAILURE",
}

export default actionTypes;
